# Starship nerd font compatible config

"$schema" = "https://starship.rs/config-schema.json"

add_newline = true

format = """
$os\
$shlvl\
${custom.giturl}\
$directory\
$all\
$fill\
$status\
$cmd_duration\
$time\
$battery\
$line_break\
$character
"""

[aws]
symbol = " "

[battery]
format = " [$symbol$percentage]($style)"

[buf]
symbol = " "

[c]
symbol = "  "

[conda]
symbol = "  "

[crystal]
symbol = "  "

[dart]
symbol = "  "

[directory]
read_only = " 󰌾 "

[docker_context]
symbol = "  "

[elixir]
symbol = " "

[elm]
symbol = "  "

[fennel]
symbol = " "

[fossil_branch]
symbol = "  "

[git_branch]
symbol = " "

[git_commit]
tag_symbol = "   "

[git_status]
conflicted = '[=$count](bold 220)'
ahead = '[⇡$count](bold 192)'
behind = '[⇣$count](bold 192)'
diverged = '[⇡$ahead_count-⇣$behind_count](bold 161)'
untracked = '[?$count](bold 45)'
stashed = '[\$$count](bold 37)'
modified = '[!$count](bold 172)'
staged = "[+$count](bold 34)"
renamed = "[»$count](bold 105)"
deleted = "[×$count](bold 198)"
format = "([$all_status$ahead_behind]($style) )"
style = "bold red"

[golang]
symbol = " "

[guix_shell]
symbol = "  "

[haskell]
symbol = "  "

[haxe]
symbol = "  "

[hg_branch]
symbol = "  "

[username]
format = "[$user]($style)"
style_user = "bold 214"

[hostname]
format = "󰁥 [$hostname$ssh_symbol]($style) "
style = "bold 36"
ssh_symbol = "  "

[java]
symbol = " "

[julia]
symbol = "  "

[kotlin]
symbol = "  "

[lua]
symbol = "  "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷  "

[nim]
symbol = "󰆥  "

[nix_shell]
symbol = "  "

[nodejs]
symbol = "󰎙 "

[ocaml]
symbol = "  "

[os]
disabled = false
format = "[$symbol]($style) "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "
format = "[$symbol$version]($style) "

[perl]
symbol = "  "

[php]
symbol = "  "

[pijul_channel]
symbol = "  "

[python]
symbol = "  "

[rlang]
symbol = "󰟔  "

[ruby]
symbol = "  "

[rust]
symbol = "󱘗 "

[scala]
symbol = " "

[swift]
symbol = "  "

[zig]
symbol = "  "

[gradle]
symbol = "  "

[time]
disabled = false
format = "  [$time]($style)"

[cmd_duration]
min_time = 10_000
format = "Δt [$duration]($style) "

[status]
disabled = false
symbol = "  "
not_executable_symbol = "  "
not_found_symbol = "󰍉 "
sigint_symbol = " "
signal_symbol = "󱠪 "
map_symbol = true

[shlvl]
disabled = false
symbol = " "

[jobs]
disabled = true

[custom.giturl]
description = "Display symbol for remote git url"
require_repo = true
when = true
format = "($output  )"
shell = ["bash", "--noprofile", "--norc"]
command = '''
remote_url=$(git remote -v | awk '{print $2}')
if [ -z "$remote_url" ]; then
  exit 1
fi
case "$remote_url" in
  *github*) 
    symbol="" ;;
  *gitlab*)
    symbol="\033[38;5;202m󰮠\033[0m" ;;
  *bitbucket*)
    symbol="\033[38;5;026m\033[0m" ;;
  *azure*)
    symbol="\033[38;5;033m\033[0m" ;;
  *aws*)
    symbol="\033[38;5;208m\033[0m" ;;
  *gitea*)
    symbol="\033[38;5;077m\033[0m" ;;
  *)
    symbol="\033[38;5;209m󰊢\033[0m" ;;
esac
echo -e $symbol
'''
